theme = "ezhil"
baseURL = "https://tiaradwptr.netlify.com/"
languageCode = "en-us"
title = "tiaradwptr"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

copyright = "© Copyright notice"

# Enable syntax highlighting.
pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
googleAnalytics = ""
# Your Disqus sortname.
disqusShortname = "tiaradwptr"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 5

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "Building footprints"

    # Content types which are included in home page recent posts list.
    mainSections = ["post"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["post"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "icons/bolin.jpg"
    avatar = "icons/bolin.jpg"

    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
    mode = "auto" # "dark" or "auto"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    #customCSS = "css/custom.css"
    # Custom CSS added to dark mode style.
    #customDarkCSS = "css/custom-dark.css"

    # Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`.
    #customJS = ["js/abc.js", "js/xyz.js"]

[permalinks]
    post = "/:slug/"
    
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post/"
weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/tiaradwiputri"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/tiaradwptr/"

[taxonomies]
   tag = "tags"